import type { YouTubeManifest } from "@/types/manifest";

export const sampleManifest: YouTubeManifest = {
  manifestId: "sample_manifest_zero_safe",
  manifestType: "youtube_search",
  platform: "youtube",
  title: "Sample manifest: YouTube metadata research",
  query: "ai agents 2026",
  source: {
    kind: "search",
    id: "ai agents 2026",
    label: "ai agents 2026",
  },
  searchSettingsSnapshot: {
    query: "ai agents 2026",
    types: ["video"],
    pageSize: 25,
    maxPages: 1,
    maxItems: 25,
    order: "relevance",
  },
  pagesFetched: 0,
  nextPageToken: null,
  quotaCostEstimate: 0,
  status: "draft",
  itemCount: 4,
  uniqueItemCount: 4,
  duplicateCount: 0,
  collectedAt: new Date("2026-05-08T00:00:00.000Z").toISOString(),
  warnings: [
    {
      code: "sample_data",
      message: "Sample metadata is shown until a server-side YouTube search is executed with YOUTUBE_API_KEY configured.",
    },
  ],
  errors: [],
  normalizedItems: [
    {
      id: "youtube:vid_000000001",
      platform: "youtube",
      itemType: "video",
      platformItemId: "vid_000000001",
      url: "https://www.youtube.com/watch?v=vid_000000001",
      title: "Building grounded AI research workflows",
      description: "A public metadata example used to demonstrate manifest cards.",
      thumbnailUrl: null,
      channelId: "UC_SAMPLE_AI",
      channelTitle: "Applied Metadata Lab",
      publishedAt: "2026-03-20T12:00:00.000Z",
      durationSeconds: 624,
      viewsCount: 0,
      likesCount: 0,
      commentsCount: 0,
      language: "en",
      region: "US",
      tags: ["ai", "metadata", "research"],
      categoryId: "28",
      isEmbeddable: true,
      liveBroadcastContent: "none",
      isShortsLike: false,
      rawJson: null,
    },
    {
      id: "youtube:vid_000000002",
      platform: "youtube",
      itemType: "shorts_like",
      platformItemId: "vid_000000002",
      url: "https://www.youtube.com/watch?v=vid_000000002",
      title: "60 second prompt safety checklist",
      description: "Short-form public metadata example.",
      thumbnailUrl: null,
      channelId: "UC_SAMPLE_AI",
      channelTitle: "Applied Metadata Lab",
      publishedAt: "2025-11-10T08:30:00.000Z",
      durationSeconds: 55,
      viewsCount: 1200,
      likesCount: 90,
      commentsCount: 8,
      language: "en",
      region: "US",
      tags: ["shorts-like", "prompting"],
      categoryId: "28",
      isEmbeddable: true,
      liveBroadcastContent: "none",
      isShortsLike: true,
      rawJson: null,
    },
    {
      id: "youtube:UC_SAMPLE_CHANNEL",
      platform: "youtube",
      itemType: "channel",
      platformItemId: "UC_SAMPLE_CHANNEL",
      url: "https://www.youtube.com/channel/UC_SAMPLE_CHANNEL",
      title: "Metadata Systems",
      description: "Example channel result.",
      thumbnailUrl: null,
      channelId: "UC_SAMPLE_CHANNEL",
      channelTitle: "Metadata Systems",
      publishedAt: "2024-02-01T10:00:00.000Z",
      durationSeconds: null,
      viewsCount: 50400,
      likesCount: null,
      commentsCount: null,
      language: "en",
      region: null,
      tags: [],
      categoryId: null,
      isEmbeddable: null,
      liveBroadcastContent: null,
      isShortsLike: false,
      rawJson: null,
    },
    {
      id: "youtube:PL_SAMPLE_PLAYLIST",
      platform: "youtube",
      itemType: "playlist",
      platformItemId: "PL_SAMPLE_PLAYLIST",
      url: "https://www.youtube.com/playlist?list=PL_SAMPLE_PLAYLIST",
      title: "Public AI research playlist",
      description: "Example playlist result.",
      thumbnailUrl: null,
      channelId: "UC_SAMPLE_CHANNEL",
      channelTitle: "Metadata Systems",
      publishedAt: "2025-05-01T10:00:00.000Z",
      durationSeconds: null,
      viewsCount: null,
      likesCount: null,
      commentsCount: null,
      language: "en",
      region: null,
      tags: [],
      categoryId: null,
      isEmbeddable: null,
      liveBroadcastContent: null,
      isShortsLike: false,
      rawJson: null,
    },
  ],
};
